### PR TITLE
Ubuntu init.d script for daemon with config file

### PR DESCRIPTION
**Pull request by william20111**
init script and config file to make this easier to deploy.

Cheers
Will

### CODE REVIEW

**Comment by afoster** [comment]
Hey Will, many thanks for this, it looks great.

The only thing I noticed is that the `binary` variable in the config doesn't seem to used in the init script itself, instead it has its own `DAEMON` variable. Was that intentional?

**Comment by william20111** [comment]
Yes it was a mistake on my part. I fixed it, along with creating the /var/run directory which on Ubuntu gets deleted at reboot. And added status option.

**Comment by afoster** [comment]
Thanks again and congrats on PR 1 :+1:

**Comment by william20111** [comment]
Cheers, and thanks for the software its working great for me just now!

**Pull request merged**
